SELECT
    league_id,
    league_season,
    match_id,
    match_week,
    SUBSTR(match_date,1,4) as match_date,
    country_code AS league_country_code,
    'description' AS champ_status,
    awayTeam_id,
    homeTeam_id,
    current_home_team_score,
    current_away_team_score,
    firstSet_home_team_score,
    firstSet_away_team_score,
    second_set_home_team_score,
    second_set_away_team_score,
    third_set_home_team_score,
    third_set_away_team_score,
    fourth_set_home_team_score,
    fourth_set_away_team_score,
    fifth_set_home_team_score,
    fifth_set_away_team_score
FROM matches
